export const MY_SKILLS = [
  {
    name: 'Java',
    icon: 'assets/icons/java-icon.svg',
    alt: 'Logo do Java',
    aosAnimation: 'zoom-out-up',
  },
  {
    name: 'Spring Boot',
    icon: 'assets/icons/springboot-icon.svg',
    alt: 'Logo do Spring Boot',
    aosAnimation: 'zoom-out-down',
  },
  {
    name: 'Typescript',
    icon: 'assets/icons/typescript-icon.svg',
    alt: 'Logo do Typescript',
    aosAnimation: 'zoom-out-up',
  },
  {
    name: 'Angular',
    icon: 'assets/icons/angular-icon.svg',
    alt: 'Logo do Angular',
    aosAnimation: 'zoom-out-down',
  },
  {
    name: 'Nodejs',
    icon: 'assets/icons/nodejs-icon.svg',
    alt: 'Logo do Nodejs',
    aosAnimation: 'zoom-out-up',
  },
  {
    name: 'Docker',
    icon: 'assets/icons/docker-icon.svg',
    alt: 'Logo do Docker',
    aosAnimation: 'zoom-out-down',
  },
  {
    name: 'Git',
    icon: 'assets/icons/git-icon.svg',
    alt: 'Logo do Git',
    aosAnimation: 'zoom-out-up',
  },
  {
    name: 'GitHub',
    icon: 'assets/icons/github-icon.svg',
    alt: 'Logo do GitHub',
    aosAnimation: 'zoom-out-up',
  },
  {
    name: 'Freelancer',
    icon: 'assets/icons/freelancer-icon.svg',
    alt: 'Logo do Freelancer',
    aosAnimation: 'zoom-out-up',
  },
  {
    name: 'Bootstrap',
    icon: 'assets/icons/bootstrap-icon.svg',
    alt: 'Logo do Bootstrap',
    aosAnimation: 'zoom-out-up',
  },
  {
    name: 'Angular Material',
    icon: 'assets/icons/angular-material-icon.svg',
    alt: 'Logo do Angular Material',
    aosAnimation: 'zoom-out-down',
  },
  {
    name: 'Tailwind',
    icon: 'assets/icons/tailwind-icon.svg',
    alt: 'Logo do Tailwind',
    aosAnimation: 'zoom-out-up',
  },
  {
    name: 'PostgreSQL',
    icon: 'assets/icons/postgresql.icon.svg',
    alt: 'Logo do PostgreSQL',
    aosAnimation: 'zoom-out-down',
  },
  {
    name: 'MySQL',
    icon: 'assets/icons/mysql-icon.svg',
    alt: 'Logo do MySQL',
    aosAnimation: 'zoom-out-down',
  },
  {
    name: 'RxJs',
    icon: 'assets/icons/rxjs-icon.svg',
    alt: 'Logo do Rxjs',
    aosAnimation: 'zoom-out-down',
  },
  {
    name: 'Scss',
    icon: 'assets/icons/scss-icon.svg',
    alt: 'Logo do SCSS',
    aosAnimation: 'zoom-out-down',
  },
  {
    name: 'Nestjs',
    icon: 'assets/icons/nestjs-icon.svg',
    alt: 'Logo do Nestjs',
    aosAnimation: 'zoom-out-down',
  },
  {
    name: 'Hibernate',
    icon: 'assets/icons/hibernate-icon.svg',
    alt: 'Logo do Hibernate',
    aosAnimation: 'zoom-out-down',
  },
  {
    name: 'Puppeteer',
    icon: 'assets/icons/puppeteer-icon.svg',
    alt: 'Logo do Puppeteer',
    aosAnimation: 'zoom-out-down',
  },
  {
    name: 'Sharp',
    icon: 'assets/icons/sharp-icon.svg',
    alt: 'Logo do Sharp',
    aosAnimation: 'zoom-out-down',
  },
  {
    name: 'Json',
    icon: 'assets/icons/json-icon.svg',
    alt: 'Logo do Json',
    aosAnimation: 'zoom-out-down',
  },
  {
    name: 'MomentJs',
    icon: 'assets/icons/momentjs.icon.svg',
    alt: 'Logo do MomentJs',
    aosAnimation: 'zoom-out-down',
  },
  {
    name: 'Swagger',
    icon: 'assets/icons/swagger.icon.svg',
    alt: 'Logo do Swagger',
    aosAnimation: 'zoom-out-down',
  },
  {
    name: 'Handlebars',
    icon: 'assets/icons/handlebars.icon.svg',
    alt: 'Logo do Handlebars',
    aosAnimation: 'zoom-out-down',
  },
];
